// Generated by sparkai-orchestrator — do not edit.
// Holds the MWM Spark Flash config (API key + SDK version), materialized at build time.
enum SparkFlashConfig {
    static let apiKey = "pk_prod_8ea7a6865941e256c1bb507522bb2b73"
    static let sdkVersion = "0.5.6"
}
